name: Fetch Faires

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  fetchJson:
    runs-on: ubuntu-latest

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Download file
        run: |
          curl -o docs/faires.json "https://makerfaire.com/query/?type=map"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
